# Generated by Django 3.2.3 on 2021-09-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('bookstore', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_phone', models.CharField(max_length=100)),
                ('cust_state', models.CharField(max_length=100)),
                ('cust_city', models.CharField(max_length=100)),
                ('cust_address', models.TextField()),
                ('rel_seller_name', models.CharField(max_length=100)),
                ('book_price', models.PositiveIntegerField()),
                ('book_total_price', models.PositiveIntegerField()),
                ('book_qty', models.PositiveIntegerField()),
                ('rel_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.bookdetail')),
                ('rel_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.users')),
                ('rel_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
